version: '2'

services:
  drupal:
    image: drupal
    ports: 
      -8080:80
    volumes:
      -v drupal-modules:/var/www/html/modules
	    -v drupal-profiles:/var/www/html/profiles
	    -v drupal-sites:/var/www/html/sites
	    -v drupal-themes:/var/www/html/themes

  postgres:
    image: postgres
    envuironment:
      -POSTGRES_PASSWORD=mypasswd

    volumes:
      drupal-modules:
      drupal-profiles:
      drupal-sites:
      drupal-themes:

