version: '2'

services:
  drupal:
    image: drupal
    ports: 
      -8080:80
    volumes:
      -v /path/on/host/modules:/var/www/html/modules
	    -v /path/on/host/profiles:/var/www/html/profiles
	    -v /path/on/host/sites:/var/www/html/sites
	    -v /path/on/host/themes:/var/www/html/themes
  postgres:
    image: postgres
    envuironment:
      -POSTGRES_PASSWORD=mypasswd


